import { useEffect, useMemo, useRef, type MutableRefObject } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import * as THREE from 'three';
import { heroSignal } from './heroSignal';
import { buildSingularity, type SingularityScene } from './singularityScene';
import { reportSceneStats } from '../lib/introAudit';

/**
 * The singularity, mounted into the site's rig.
 *
 * The object is generated by `singularityScene` (see the note there on why the
 * GLB was abandoned). This component owns only three things the prototype
 * could not know about:
 *
 *  - **Framing.** The prototype auto-framed a 45° camera to the object's
 *    bounds. The site uses a 20° lens at distance 6.0 on purpose — a long lens
 *    keeps the disc near edge-on, so the object reads as a black hole rather
 *    than a planet with rings. The generated model is therefore normalised to
 *    the same `targetSize` the GLB was, which keeps the hero composition
 *    exactly where it was; the prototype's own `model.position` offset is
 *    dropped, because placement belongs to `renderQuality.frame`.
 *  - **The site's frame loop.** One Lenis, one ticker, one rAF: nothing here
 *    starts a `requestAnimationFrame` of its own.
 *  - **`heroSignal`.** The intro's transient, composed on top of the object's
 *    resting breathing rather than replacing it.
 */
interface Props {
  idle: boolean;
  targetSize: number;
  /** Raw pointer target, owned by the rig — damped inside the object. */
  pointerRef: MutableRefObject<{ x: number; y: number }>;
}

export function SingularityModel({ idle, targetSize, pointerRef }: Props) {
  const breath = useRef<THREE.Group>(null);
  const camera = useThree((s) => s.camera);

  const scene = useMemo<SingularityScene>(() => buildSingularity(), []);

  /**
   * Normalised exactly the way the GLB was: bounding-box diagonal scaled to
   * `targetSize` and re-centred, so swapping the bake for the generator does
   * not move the composition. Measured once, with the lens rig at identity —
   * it is billboarded every frame and its box would otherwise be unstable.
   */
  const { offset, scale } = useMemo(() => {
    const box = new THREE.Box3().setFromObject(scene.group);
    const size = box.getSize(new THREE.Vector3()).length();
    const center = box.getCenter(new THREE.Vector3());
    return {
      offset: [-center.x, -center.y, -center.z] as [number, number, number],
      scale: targetSize / (size || 1),
    };
  }, [scene, targetSize]);

  useEffect(() => {
    reportSceneStats(scene.stats);
    return () => scene.dispose();
  }, [scene]);

  const still = useRef({ x: 0, y: 0 });

  useFrame((state, delta) => {
    const now = state.clock.getElapsedTime() * 1000;
    const dt = Math.min(0.05, delta);
    scene.update(dt, now, camera, idle ? pointerRef.current : still.current, heroSignal);

    const node = breath.current;
    if (node) node.scale.setScalar(1 + heroSignal.swell);
  });

  return (
    // Framing scale and the intro's swell are separate groups on purpose: the
    // frame loop owns the inner one and would otherwise overwrite the framing.
    <group scale={scale}>
      <group ref={breath}>
        <primitive object={scene.group} position={offset} />
      </group>
    </group>
  );
}
